# Generated by Django 5.0.1 on 2024-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondue_app', '0002_alter_user_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
