# Generated by Django 5.0.1 on 2024-02-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondue_app', '0003_alter_user_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
